micronaut:
  application:
    name: greeter
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/greeterdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'awesome'